### ISSUE TITLE
Sort opponents by ELO

### ISSUE THREAD

**Issue by jcwhisman** [DestinyTrialsReport/DestinyTrialsReport#127]
Not sure where to make a proper suggestion, however....

I think it would be a great idea in opponents.destinytrialsreport.com to be able to sort opponents by ELO instead of just KDR.

I understand that it would make the call take longer to retrieve that info. But I know a lot of us use it so we can see if we played any of the top players in the game!

**Comment by v-fedorov** [comment]
Suggestions here are fine :)

The reason we cant is because we don't actually have Elo data in our database so theres no way we can retrieve that without making calls to guardian.gg for each opponent.
Its not uncommon for the average player to have over 1000 opponents already so we wouldnt want to spam guardian.gg with that many requests and possibly cause issues
